In [1]:
# NLTK check
import nltk
nltk.__version__

'3.8.1'

CountVectorizer : 단어 빈도수를 이용한 벡터화

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vector = CountVectorizer()

vector.fit(corpus)
print(f'[Vocabulary_단어 인덱스] : {vector.vocabulary_}')

result = vector.transform(corpus).toarray()
print(f'[변환된 데이터 배열] : {result}')


[Vocabulary_단어 인덱스] : {'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
[변환된 데이터 배열] : [[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [3]:
# 단어 사전에서 단어만 추출
print(f'[단어 사전] : {vector.get_feature_names_out()}')    

[단어 사전] : ['and' 'document' 'first' 'is' 'one' 'second' 'the' 'third' 'this']


In [4]:
# 단어사전 기반으로 문장 ==> 수치화
result = vector.transform(corpus)

print(result, result.toarray(), sep='\n')

# 모든 단어를 알파벳순 정렬
# (문장, 단어) 형태의 인덱스로 해당 문장에 존재하는 단어의 빈도수를 출력
# This is the first document.
# [ 0 1 1 1 0 0 1 0 1]
# and document first is one second the third this

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 6)	1
  (0, 8)	1
  (1, 1)	2
  (1, 3)	1
  (1, 5)	1
  (1, 6)	1
  (1, 8)	1
  (2, 0)	1
  (2, 3)	1
  (2, 4)	1
  (2, 6)	1
  (2, 7)	1
  (2, 8)	1
  (3, 1)	1
  (3, 2)	1
  (3, 3)	1
  (3, 6)	1
  (3, 8)	1
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


TF-IDF

In [5]:
# TFIDF 인스턴스 생성
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)

TfidfVectorizer()

In [6]:
# 단어 사전 확인
print(f'[단어 사전:인덱스]\n{vectorizer.vocabulary_}')
print(f'[단어 사전:단어 IDF]\n{vectorizer.idf_}')

[단어 사전:인덱스]
{'this': 8, 'is': 3, 'the': 6, 'first': 2, 'document': 1, 'second': 5, 'and': 0, 'third': 7, 'one': 4}
[단어 사전:단어 IDF]
[1.91629073 1.22314355 1.51082562 1.         1.91629073 1.91629073
 1.         1.91629073 1.        ]


In [7]:
vectorizer.transform(corpus).toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

코사인 유사도

In [8]:
# Cosine Similarity
from sklearn.feature_extraction.text import TfidfTransformer

doc_list = [
    'if you take the blue pill, the story ends',
    'if you take the red pill, you stay in Wonderland',
    'if you take the red pill, I show you how deep the rabbit hole goes']

tfidf_vect = TfidfVectorizer()
feature_vect = tfidf_vect.fit_transform(doc_list)
feature_vect

<3x18 sparse matrix of type '<class 'numpy.float64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [9]:
from sklearn.metrics.pairwise import cosine_similarity

# cosine_similarity()로 코사인 유사도 계산
# - X : 비교 기준 (행렬)
# - y : 바교하고자 하는 문서 (행렬)

result = cosine_similarity(feature_vect[0], feature_vect)
print(result)

[[1.         0.40207758 0.40425045]]
