In [19]:
# winequality-white.csv 를 불러오기
import torch
import pandas as pd

wine_data = pd.read_csv("winequality-white.csv", sep=";")
wine_tensor = torch.tensor(wine_data.values)
print(wine_data.shape)
print(wine_data.head(2))
print(wine_tensor.shape)
wine_tensor

(4898, 12)
   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   

   free sulfur dioxide  total sulfur dioxide  density   pH  sulphates  \
0                 45.0                 170.0    1.001  3.0       0.45   
1                 14.0                 132.0    0.994  3.3       0.49   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
torch.Size([4898, 12])


tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]],
       dtype=torch.float64)

In [24]:
# DF -> tensor 시 .values 필요
# wine_tensor_2 = torch.tensor(wine_data) => 인식 불가

근데 마지막 열을 제거해야한다

In [21]:
feature_data = wine_data.drop(wine_data.columns[-1], axis=1)
feature_data.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   

   free sulfur dioxide  total sulfur dioxide  density   pH  sulphates  alcohol  
0                 45.0                 170.0    1.001  3.0       0.45      8.8  
1                 14.0                 132.0    0.994  3.3       0.49      9.5

In [23]:
feature_tensor = torch.tensor(feature_data.values)
feature_tensor.shape

torch.Size([4898, 11])

<hr> 

교재 : numpy -> 나도 넘파이로 따라가기

In [30]:
# np로 데이터 저장
import numpy as np

wine_np = np.loadtxt("winequality-white.csv", delimiter=";", dtype=np.float32, skiprows=1)
wine_np.shape

(4898, 12)

In [ ]:
# torch로 저장


In [35]:
# feature
feature_tensor = torch.from_numpy(wine_np[:, :-1])
feature_tensor.shape

torch.Size([4898, 11])

In [37]:
# target
# .long() : transform into 64bit
target_tensor = torch.from_numpy(wine_np[:, -1]).long()
target_tensor

tensor([6, 6, 6,  ..., 6, 7, 6])

<hr>

##### Tip💡 : 메서드에 _ 를 추가하면 inplace와 같은 의미!

In [40]:

t1 = torch.tensor([-1, -2])
t1, t1.abs(), t1

(tensor([-1, -2]), tensor([1, 2]), tensor([-1, -2]))

In [42]:
t1.abs_(), t1   # 원본이 바뀐다!

(tensor([1, 2]), tensor([1, 2]))

임베딩 : 큰 데이터를 압축된 일부 데이터만으로 구분 가능하게 만든 것  
       -> 모듈에서 해줌!