### 텐서 살펴보기
Pytorch에서 데이터 저장 자료형  
모델 입력, 출력 데이터 형태

1. 데이터 준비

In [3]:
# Load Module
import torch

Tensor 속성 관련 함수

In [4]:
# 매개변수 : 텐서 인스텐스, 텐서 변수명
def print_attribute(tensor, name):
    print(f'[ Tensor {name}\'s Attribute ]')
    print(f' - tensor.shape : {tensor.shape}')
    print(f' - tensor.ndim : {tensor.ndim}D')
    print(f' - tensor.dtype : {tensor.dtype}')
    print(f' - tensor.device : {tensor.device}')
    print(f' - tensor.requires_grad : {tensor.requires_grad}')
    print(f' - tensor.data :\n{tensor.data}')

Tensor 생성 (1) 특정 데이터 타입의 텐서 생성
- 타입별 텐서 클래스 생성자 활용
- 예) IntTensor(), FloatTensor(), DoubleTensor()

In [5]:
# 정수 타입 텐서 생성
t1 = torch.IntTensor(10)
t2 = torch.IntTensor([10.2, 20.])
t3 = torch.BoolTensor([1, 0, 1, -1])
t4 = torch.FloatTensor([10, 20])

C:\Users\wjs31\AppData\Local\Temp\ipykernel_45476\2411395638.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  t2 = torch.IntTensor([10.2, 20.])


In [6]:
for idx, i in enumerate([t1, t2, t3, t4]):
    print_attribute(i, 't'+f'{idx+1}')
    print()

[ Tensor t1's Attribute ]
 - tensor.shape : torch.Size([10])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([1602228592,       1304,          0,          0,          0,          0,
                 0,          0,          0,          0], dtype=torch.int32)

[ Tensor t2's Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([10, 20], dtype=torch.int32)

[ Tensor t3's Attribute ]
 - tensor.shape : torch.Size([4])
 - tensor.ndim : 1D
 - tensor.dtype : torch.bool
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([ True, False,  True,  True])

[ Tensor t4's Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([10., 20.])



In [7]:
#  IntTensor : 실수(10.2)를 넣어도 정수 타입으로 잡힘  
#  FloatTensor : 정수 넣어도 실수 타입 반환

<hr>

Tensor 생성 (2) 원하는 값으로 생성 => torch.tensor()

In [8]:
t1 = torch.tensor(10)
t2 = torch.tensor(10.1)
t3 = torch.tensor([10, 20])
t4 = torch.tensor([[10, 20], [30, 40]])
t1_2 = torch.tensor(10, dtype=torch.float32)
t1_3 = torch.tensor(10, dtype=torch.bool)

for idx, i in enumerate([t1, t2, t3, t4, t1_2, t1_3]):
    print_attribute(i, 't'+f'{idx+1}')
    print()

[ Tensor t1's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
10

[ Tensor t2's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
10.100000381469727

[ Tensor t3's Attribute ]
 - tensor.shape : torch.Size([2])
 - tensor.ndim : 1D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([10, 20])

[ Tensor t4's Attribute ]
 - tensor.shape : torch.Size([2, 2])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int64
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([[10, 20],
        [30, 40]])

[ Tensor t5's Attribute ]
 - tensor.shape : torch.Size([])
 - tensor.ndim : 0D
 - tensor.dtype : torch.float32
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
10.0



In [9]:
# 자동으로 데이터 타입 지정
# 임의 데이터 타입 지정 가능 : 
#   - .float or .int
#   - .int8 등으로 용량 줄이기

Tensor 생성 (3) 특정 값으로 채우기

In [10]:
t1 = torch.zeros(2, 2, dtype=torch.int8)
t2 = torch.ones(2, 2, dtype=torch.int8)
t3 = torch.full((2, 2), 10, dtype=torch.int8)
t4 = torch.eye(2, dtype=torch.int8)
t5 = torch.eye(1, 3)                    # tensor([[1., 0., 0.]])
t6 = torch.arange(10, dtype=torch.int8) # GeeX 추천 ; tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

for idx, i in enumerate([t1, t2, t3, t4, t5, t6]):
    print_attribute(i, 't'+f'{idx+1}')
    print()

[ Tensor t1's Attribute ]
 - tensor.shape : torch.Size([2, 2])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([[0, 0],
        [0, 0]], dtype=torch.int8)

[ Tensor t2's Attribute ]
 - tensor.shape : torch.Size([2, 2])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

[ Tensor t3's Attribute ]
 - tensor.shape : torch.Size([2, 2])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([[10, 10],
        [10, 10]], dtype=torch.int8)

[ Tensor t4's Attribute ]
 - tensor.shape : torch.Size([2, 2])
 - tensor.ndim : 2D
 - tensor.dtype : torch.int8
 - tensor.device : cpu
 - tensor.requires_grad : False
 - tensor.data :
tensor([[1, 0],
        [0, 1]], dtype=torch.int8)

[ Tensor t5's Attribute ]
 - tensor.shape : torch.Si

In [11]:
# 이미 존재하는 텐서와 동일한 shape으로 잡고 값 채우기 => zero_like(), ones_like()
img = torch.Tensor([[2, 3, 4, 5, 6, 7], [2, 3, 4, 5, 6, 7]])
print(img.shape)

torch.Size([2, 6])


In [12]:
zero_img = torch.zeros_like(img)
print(zero_img)     # 동일한 shape으로 1을 채움

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])


In [13]:
full_img = torch.full_like(img, 7)
print(full_img)

tensor([[7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7.]])


In [14]:
# 대각선 방향으로 1 채우기 => eye()
t1 = torch.eye(7, dtype=torch.int8)
print(t1)

tensor([[1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 1]], dtype=torch.int8)


Tensor 생성 (4) 랜덤 값 채우기

In [15]:
torch.manual_seed(12)
t1 = torch.rand(2, 3)       # [0, 1) 사이
t2 = torch.randn(2, 3)      # Standard Normal 분포에서 랜덤 생성
t3 = torch.randint(low=1, high=10, size=(2, 3))     # low <= x , high

for idx, i in enumerate([t1, t2, t3]):
    print(i)

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272]])
tensor([[ 1.5869,  1.1268, -1.2274],
        [-0.8216, -1.7861,  0.6167]])
tensor([[8, 4, 6],
        [2, 2, 2]])


Tensor 생성 방법 (5) : Ndarray 객체 활용 => torch.from_numpy(), torch.as_tensor(), tensor()

In [16]:
# 데이터 생성
import numpy as np

data = np.array([11, 22, 33])
print(data, data.dtype)

[11 22 33] int32


In [17]:
t1 = torch.from_numpy(data)
t2 = torch.as_tensor(data)
t3 = torch.tensor(data)

for i in [t1, t2, t3]:
    print(i)

tensor([11, 22, 33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


In [18]:
# 원소 변경
data[0] = 100
data

array([100,  22,  33])

In [19]:
for i in [t1, t2, t3]:
    print(i)
    
# from_numpy(), as_tensor() => 데이터 공유 (원본따라 변경)
# tensor() => 복사본 생성 (원본과 분리)

tensor([100,  22,  33], dtype=torch.int32)
tensor([100,  22,  33], dtype=torch.int32)
tensor([11, 22, 33], dtype=torch.int32)


In [21]:
# fin, 연산 부분은 02 파일에