### 인덱싱과 슬라이싱, 연산

In [2]:
import numpy as np
import torch

In [9]:
points = torch.tensor([[4, 2], [5, 3], [6,4]], dtype=torch.int16)

In [14]:
# 텐서의 원소 1개 접근
# 데이터 3 추출
print(points[1, 1])
# 마지막 4 추출
print(points[-1, -1])
# 1번 행부터 나머지 모든 행 추출
print(points[1:])

tensor(3, dtype=torch.int16)
tensor(4, dtype=torch.int16)
tensor([[5, 3],
        [6, 4]], dtype=torch.int16)


In [18]:
# randn 설명 (신기하다)
print(torch.randn(2, 3))
print(torch.randn(2, 3, 1))        # (3,1)이 2개        
print(torch.randn(2, 2, 3, 1))     # (3,1) 2개가 2개    (배치, 층, 행, 열)

tensor([[-0.2398, -0.7151,  0.1491],
        [-0.4795,  1.2635,  0.4994]])
tensor([[[-1.2539],
         [ 0.1546],
         [-1.7640]],

        [[ 1.2387],
         [-1.6125],
         [ 1.4627]]])
tensor([[[[ 0.4086],
          [-0.8017],
          [-1.1879]],

         [[ 0.0696],
          [ 1.0405],
          [-0.0313]]],


        [[[ 1.2275],
          [-1.3613],
          [ 0.2629]],

         [[-0.9269],
          [-0.0401],
          [ 0.2373]]]])


브로드캐스팅 : 크기 다른 행렬들 사칙연산 수행

In [20]:
# Case 1 : 같은 크기 행렬
m1 = torch.FloatTensor([[2, 3]])    # [1,2]
m2 = torch.FloatTensor([[4, 5]])
print(m1.shape)
m3 = m1 + m2
print(m3, m3.shape)

torch.Size([1, 2])
tensor([[6., 8.]]) torch.Size([1, 2])


In [23]:
# Case 2 : 벡터와 행렬
m1 = torch.FloatTensor([[2, 3]])
m2 = torch.FloatTensor([4])        # [1]
print(m2.shape)
m3 = m1 + m2
print(m3, m3.shape)     # [6., 7.] => 둘 다 적용

torch.Size([1])
tensor([[6., 7.]]) torch.Size([1, 2])


In [25]:
# Case 3 : 크기 다른 두 행렬
m1 = torch.FloatTensor([[2, 3]])    # (1, 2)
m2 = torch.FloatTensor([[4], [5]])  # (2, 1)
print(m2.shape)
m3 = m1 + m2
print(m3, m3.shape)     # 각 요소에 적용 : 행렬 방식

torch.Size([2, 1])
tensor([[6., 7.],
        [7., 8.]]) torch.Size([2, 2])


In [29]:
m3 = m1 * m2
m4 = m1.mul(m2)     #   곱하기 연산
print(m3, '\n', m3.shape)
print(m4, '\n', m4.shape)

tensor([[ 8., 12.],
        [10., 15.]]) 
 torch.Size([2, 2])
tensor([[ 8., 12.],
        [10., 15.]]) 
 torch.Size([2, 2])


In [30]:
# 원소 단위 연산자 .add .sub .mul .div
m1.add(m2), m1.sub(m2), m1.mul(m2), m1.div(m2)

(tensor([[6., 7.],
         [7., 8.]]),
 tensor([[-2., -1.],
         [-3., -2.]]),
 tensor([[ 8., 12.],
         [10., 15.]]),
 tensor([[0.5000, 0.7500],
         [0.4000, 0.6000]]))

In [31]:
# 점심시간! fin