#### 텐서 연결 & 결합

In [2]:
import torch

In [11]:
# 텐서 데이터 생성
torch.manual_seed(12)

X = torch.rand(2, 10)   # 임의의 0 ~ 1 실수
y = torch.randint(0, 2, (10, )) # low ~ high, shape -> 0 or 1
y2 = torch.randint(0, 2, (2, 10))
X, y, y2

(tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
          0.7224],
         [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
          0.4456]]),
 tensor([0, 1, 0, 0, 1, 0, 1, 1, 0, 0]),
 tensor([[1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
         [0, 0, 1, 1, 1, 1, 0, 0, 0, 0]]))

In [10]:
print(f'X -> {X.shape}, {X.ndim}D')
print(f'y -> {y.shape}, {y.ndim}D')
print(f'y2 -> {y2.shape}, {y2.ndim}D')

X -> torch.Size([2, 10]), 2D
y -> torch.Size([10]), 1D
y2 -> torch.Size([2, 10]), 2D


In [21]:
# tensor 연결 .cat
xy1 = torch.cat([X, y2], dim=1)
print(xy1)
print(xy1.size())
print(xy1.ndim)

tensor([[0.4657, 0.2328, 0.4527, 0.5871, 0.4086, 0.1272, 0.6373, 0.2421, 0.7312,
         0.7224, 1.0000, 1.0000, 0.0000, 1.0000, 1.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000],
        [0.1992, 0.6948, 0.5830, 0.6318, 0.5559, 0.1262, 0.9790, 0.8443, 0.1256,
         0.4456, 0.0000, 0.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
         0.0000, 0.0000]])
torch.Size([2, 20])
2


In [16]:
# tensor 연결 .stack
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
torch.stack([x, y, z])
torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [24]:
# max 값 : dim=1 => 1
max_value = xy1.max(dim=1)[0]   # '행' 중에서 최대; axis=1 와 반대!
max_index = xy1.max(dim=1)[1]   
print(max_value, max_index)     # 집계 연산이므로

tensor([1., 1.]) tensor([10, 12])


In [25]:
# dim=0 -> 전체 
max_value = xy1.max(dim=0)[0]   # '열' 중에서 최대
max_index = xy1.max(dim=0)[1]
print(max_value, max_index)     # 집계함수(max, sum, mode, mean 등등)는 항상 이 형식이다

tensor([0.4657, 0.6948, 0.5830, 0.6318, 0.5559, 0.1272, 0.9790, 0.8443, 0.7312,
        0.7224, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0000, 0.0000,
        0.0000, 0.0000]) tensor([0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])


In [26]:
# 다시 tensor4로 돌아감