In [1]:
### 

In [2]:
# Weight initialization
import torch
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(8, 4)
        self.fc2 = nn.Linear(4, 2)
        self.fc3 = nn.Linear(2, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        return x
    
    # 강사님 코드
    # def forward(self, x):
    #     return self.fc3(self.fc2(self.fc1(x)))

Create Model instance

In [7]:
# Create Model Instance
model = Net()

# Check attributes
print(model.fc1.weight)

Parameter containing:
tensor([[-0.0737, -0.2465,  0.1391, -0.1397,  0.1616, -0.0875, -0.2610,  0.3344],
        [-0.1374, -0.0259, -0.3003, -0.2538,  0.1562, -0.1993,  0.1338, -0.0757],
        [-0.0462,  0.3318, -0.2704,  0.3306, -0.1283, -0.0903, -0.1130,  0.2921],
        [ 0.2102, -0.0504, -0.2849, -0.1653, -0.2552, -0.1747, -0.3002,  0.0139]],
       requires_grad=True)


In [9]:
model.fc1

Linear(in_features=8, out_features=4, bias=True)

Parameters 확인하기

In [10]:
for param in model.parameters():
    print(param, end='\n\n')

# .parameters() method returns an iterator over module parameters => have to use for loop

Parameter containing:
tensor([[-0.0737, -0.2465,  0.1391, -0.1397,  0.1616, -0.0875, -0.2610,  0.3344],
        [-0.1374, -0.0259, -0.3003, -0.2538,  0.1562, -0.1993,  0.1338, -0.0757],
        [-0.0462,  0.3318, -0.2704,  0.3306, -0.1283, -0.0903, -0.1130,  0.2921],
        [ 0.2102, -0.0504, -0.2849, -0.1653, -0.2552, -0.1747, -0.3002,  0.0139]],
       requires_grad=True)

Parameter containing:
tensor([ 0.3327,  0.1590, -0.2474, -0.1727], requires_grad=True)

Parameter containing:
tensor([[ 0.1164,  0.2911, -0.2814, -0.4653],
        [ 0.0347,  0.2670, -0.4503,  0.4388]], requires_grad=True)

Parameter containing:
tensor([-0.2028, -0.3291], requires_grad=True)

Parameter containing:
tensor([[-0.2309, -0.1969]], requires_grad=True)

Parameter containing:
tensor([0.3836], requires_grad=True)



In [14]:
# But we don't know the name of the parameters : .named_parameters() method
# 모델 각 층별 W, b 확인
for name, param in model.named_parameters():
    print(name, param, end='\n\n')

fc1.weight Parameter containing:
tensor([[ 0.0835, -0.5888, -0.5067,  0.4745, -0.0378,  0.2991, -0.6782, -0.0997],
        [-0.1608,  0.3889, -0.0752,  0.4890,  0.4044,  0.0042, -0.5556, -0.2057],
        [ 0.2228, -0.2310,  0.6308,  0.5236, -0.3496, -0.3436,  0.4984, -0.2262],
        [ 0.1454, -0.2981,  0.0799, -0.1087, -0.1138,  0.1765, -0.2492, -0.7047]],
       requires_grad=True)

fc1.bias Parameter containing:
tensor([ 0.3327,  0.1590, -0.2474, -0.1727], requires_grad=True)

fc2.weight Parameter containing:
tensor([[ 0.1164,  0.2911, -0.2814, -0.4653],
        [ 0.0347,  0.2670, -0.4503,  0.4388]], requires_grad=True)

fc2.bias Parameter containing:
tensor([-0.2028, -0.3291], requires_grad=True)

fc3.weight Parameter containing:
tensor([[-0.2309, -0.1969]], requires_grad=True)

fc3.bias Parameter containing:
tensor([0.3836], requires_grad=True)



In [15]:
# 이제 이걸 opimizer에 넣어서 학습을 시키면 됨

Layer 가중치 설정

In [20]:
# Layer Weight Initialization : 세비어 알고리즘으로 초기화
# - uniform_ : inplace와 같은 말
print(nn.init.xavier_uniform_(model.fc1.weight))
print(nn.init.xavier_normal_(model.fc1.weight))

Parameter containing:
tensor([[-0.3231,  0.2160, -0.5479, -0.2011,  0.2111,  0.1731, -0.4093, -0.6172],
        [-0.6861,  0.3510, -0.3353, -0.0637, -0.4499,  0.1799, -0.5902,  0.0026],
        [ 0.2835,  0.3896, -0.3162, -0.0743,  0.5827,  0.0427, -0.5057,  0.0155],
        [-0.2339,  0.1367,  0.1956,  0.6987,  0.0144,  0.4216,  0.2146, -0.4484]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.1231,  0.5636,  0.0315, -0.1863, -0.6883,  0.3614,  0.2530, -0.2425],
        [-0.3115, -0.0725,  0.3068, -0.1292,  0.3085,  0.0371, -0.4480, -0.5644],
        [-0.7895,  0.7087, -0.0876,  0.2714, -0.1825,  0.4090,  0.6595,  0.1761],
        [ 0.2472,  0.5612,  0.1333, -0.3594, -0.9065, -0.3974,  0.3337, -0.2147]],
       requires_grad=True)


In [22]:
# 헤 알고리즘으로 초기화 : .kaiming_uniform_() method
print(nn.init.kaiming_uniform_(model.fc1.weight))
print(nn.init.kaiming_normal_(model.fc1.weight))

Parameter containing:
tensor([[ 0.4559, -0.4614, -0.1921, -0.6967,  0.4317,  0.7838,  0.5788, -0.6705],
        [-0.8409,  0.6749,  0.0622,  0.4947, -0.1938,  0.7961, -0.3015,  0.3056],
        [ 0.0357, -0.0348, -0.7893, -0.0212, -0.0684,  0.1228, -0.4919, -0.0445],
        [-0.2800, -0.6831,  0.0300,  0.1652, -0.8040,  0.6348, -0.2394, -0.5648]],
       requires_grad=True)
Parameter containing:
tensor([[-0.1967,  0.1419,  0.1145, -0.0385, -0.8435,  0.6116,  0.4025, -0.0867],
        [-0.6370, -0.1491, -0.5232,  0.1921, -0.4305, -0.2471, -0.7467, -0.0566],
        [-0.5473, -0.5791,  0.2884, -0.5220, -0.1187, -0.5314,  0.9394, -0.6911],
        [-0.3961,  0.9242, -0.1629, -0.2890,  0.2372,  0.4482,  0.0137,  0.0821]],
       requires_grad=True)


uniform_과 normal_의 차이  
: uniform_은 균일 분포에서 랜덤하게 값을 뽑아내고, normal은 정규 분포에서 랜덤하게 값을 뽑아낸다.

In [24]:
# 모델 구성 모든 층 가져오기
for child in model.children():
    print(child, end='\n\n')
    
for child in model.named_children():    # 이름도 같이 출력
    print(child, end='\n\n')            # ('fc1', Linear(in_features=8, out_features=4, bias=True))

Linear(in_features=8, out_features=4, bias=True)

Linear(in_features=4, out_features=2, bias=True)

Linear(in_features=2, out_features=1, bias=True)

('fc1', Linear(in_features=8, out_features=4, bias=True))

('fc2', Linear(in_features=4, out_features=2, bias=True))

('fc3', Linear(in_features=2, out_features=1, bias=True))



In [29]:
# torchinfo로 모델 구조 확인
from torchinfo import summary

# summary(model, input_size=(1, 8))
summary(model)

Layer (type:depth-idx)                   Param #
Net                                      --
├─Linear: 1-1                            36
├─Linear: 1-2                            10
├─Linear: 1-3                            3
Total params: 49
Trainable params: 49
Non-trainable params: 0

<hr><hr>

##### 오후 수업

In [30]:
# model 저장
torch.save(model.state_dict(), 'model.pt')

In [31]:
# model 불러오기
my_model = Net()
my_model.load_state_dict(torch.load('model.pt'))
print(my_model)

Net(
  (fc1): Linear(in_features=8, out_features=4, bias=True)
  (fc2): Linear(in_features=4, out_features=2, bias=True)
  (fc3): Linear(in_features=2, out_features=1, bias=True)
)


In [ ]:
# 