In [1]:
import numpy as np

In [23]:
# 1. Generate ndarray type data
print('1-1.')
# 1) filled with 0
print(np.zeros(2))
print()
# 2) filled with 1
print('1-2.')
print(np.ones(10), np.ones(10, dtype=int))
print(np.ones((2, 5), dtype=np.bool_))
print()
# 3) filled with a random number
print('1-3.')
print(np.random.randint(1, 15, (2, 5)))
# 4) 0 <= x < 1
print('1-4.')
print(np.random.rand(2, 5))
print()
# 5) normal distribution
print('1-5.')
print(np.random.randn(2, 5))
print()
# 6) shuffle
print('1-6.')
a = np.arange(10)
print(a)
np.random.shuffle(a)    # shuffle in place : no return value
print(a)
print()
# 7) linspace : start, end, number of elements
print('1-7.')
print(np.linspace(0, 1, 5))     # seperated equally
print()

1-1.
[0. 0.]

1-2.
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [1 1 1 1 1 1 1 1 1 1]
[[ True  True  True  True  True]
 [ True  True  True  True  True]]

1-3.
[[13  2 10  6  2]
 [11  9  4  6  6]]
1-4.
[[0.88453942 0.60320224 0.84452318 0.65646265 0.97351427]
 [0.81496859 0.17079719 0.58010088 0.33799674 0.70806874]]

1-5.
[[ 0.43652245  0.79544455  0.46450325 -0.49364655 -1.87913635]
 [ 0.73041199 -1.69194614 -1.51322706  1.24126754 -0.29948311]]

1-6.
[0 1 2 3 4 5 6 7 8 9]
[1 3 5 4 2 8 6 9 0 7]

1-7.
[0.   0.25 0.5  0.75 1.  ]



In [27]:
data = np.random.rand(2, 5)
print(data.sum())
print(data.mean())
print(data.max())
print(data.base)    # .base : return the original data; if it's original, return None

4.134586981198687
0.41345869811986874
0.6231585931655167
None


In [30]:
print('1.', data.argmax())    # return the index of the maximum value
print('2.', data.argmin())    # return the index of the minimum value
print('3.', data.cumsum())    # return the cumulative sum
print('4.', data.cumprod())    # return the cumulative product
print('5.', data.std())    # return the standard deviation


1. 9
2. 3
3. [0.3191008  0.86453206 1.45981987 1.52759155 1.80629925 2.30465127
 2.83933689 2.94590659 3.51142839 4.13458698]
4. [3.19100804e-01 1.74047551e-01 1.03608386e-01 7.02171457e-03
 1.95700592e-03 9.75277844e-04 5.21467044e-04 5.55725854e-05
 3.14275084e-05 1.95843219e-05]
5. 0.19499237757857987


In [37]:
# strides : 메모리 이동 단위 (dim 간의 간격 / 요소 간의 간격)
print(data)
print(data.strides)   # (40, 8) : 40 bytes for row, 8 bytes for column
# 데이터는 (2,5)인데 40인 이유 : 8바이트 * 5개 = 40바이트; 8바이트는 double형의 크기
print()

# order : 열 우선 저장 (C) / 행 우선 저장 (F)
print(data.flags.c_contiguous)  # True: 열 우선 저장이란 뜻
print(data.flags.f_contiguous)  # False: 행 우선 저장이란 뜻

[[0.3191008  0.54543125 0.59528782 0.06777168 0.2787077 ]
 [0.49835201 0.53468563 0.1065697  0.5655218  0.62315859]]
(40, 8)
True
False


In [40]:
# 객체 생성 매개변수 분석
object = np.random.randint(1, 15, (2, 5))
np.array(object, dtype=None, copy=True, order='C', subok=False, ndmin=0, like=None)
# dtype : 데이터 타입 지정; None일 경우 자동으로 결정
# copy : 복사 여부; True일 경우 복사본 생성
print('Copy=True :', np.array(object, copy=True))
print('Copy=False :', np.array(object, copy=False))
print()
# order : 저장 순서 (C / F); K : like에 의해 결정
print('Order=C :', np.array(object, order='C'))
print('Order=F :', np.array(object, order='F'))
print('Order=K :', np.array(object, order='K'))
print()
# subok : 하위 클래스 생성 여부
print('Subok=True :', np.array(object, subok=True))
print('Subok=False :', np.array(object, subok=False))
print()
# ndmin : 최소 차원; 0일 경우 최소 차원으로 생성, 2일 경우 2차원으로 생성
print('Ndmin=0 :', np.array(object, ndmin=0))
print('Ndmin=2 :', np.array(object, ndmin=2))
print()
# like : 생성할 배열과 같은 속성을 가진 배열 생성
print('Like=object :', np.array(object, like=object))
print('Like=data :', np.array(object, like=data))
print()

Copy=True : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]
Copy=False : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]

Order=C : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]
Order=F : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]
Order=K : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]

Subok=True : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]
Subok=False : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]

Ndmin=0 : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]
Ndmin=2 : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]

Like=object : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]
Like=data : [[ 5  8 12 10  1]
 [ 2 11  4  8  9]]

